name: " Tarea"
description: "Tarea de desarrollo o mantenimiento"
title: "chore: "
labels: ["task"]
body:
  - type: input
    id: titulo
    attributes:
      label: "Nombre de la tarea"
      placeholder: "Ej: Configurar migraciones de base de datos"
    validations:
      required: true
  - type: textarea
    id: descripcion
    attributes:
      label: "Descripci贸n"
      placeholder: "Describe lo que se debe hacer..."
    validations:
      required: true
  - type: dropdown
    id: tipo
    attributes:
      label: "Tipo de tarea"
      options:
        - Configuraci贸n
        - Documentaci贸n
        - Refactorizaci贸n
        - Testing
        - Deployment
    validations:
      required: true